
@startuml ObjectMagicFit
object utilisateur1 {
  nom = "Yassine"
  email = "yassine@example.com"
}

object coach1 {
  nom = "Coach Amine"
  specialite = "Musculation"
}

object exercice1 {
  nom = "Développé couché"
  repetitions = 10
  series = 4
}

object programme1 {
  titre = "Programme Prise de masse"
  niveau = "Intermédiaire"
}

utilisateur1 --> programme1
programme1 --> exercice1
coach1 --> programme1
@enduml
