
@startuml ActivityMagicFit
start
:Se connecter;
if (Infos valides ?) then (oui)
  :Afficher interface;
  :Voir programmes;
  :Choisir un programme;
  :Commencer programme;
  :Saisir performance;
  :Envoyer performance;
  :Recevoir feedback;
else (non)
  :Afficher erreur;
endif
stop
@enduml
