
@startuml DeploymentMagicFit
node "Client Web" {
  component "Navigateur Angular"
}

node "Serveur Web" {
  component "API Laravel"
}

node "Base de Données" {
  database "MySQL"
}

node "Raspberry Pi (Smart Mirror)" {
  component "Module MMM-InteractiveMap"
}

"Navigateur Angular" --> "API Laravel"
"API Laravel" --> "MySQL"
"API Laravel" --> "Module MMM-InteractiveMap"
@enduml
